### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by amontoison** [JuliaSmoothOptimizers/QuadraticModels.jl#131]
@tmigot
You added support for ADNLPModels.jl v0.8.0 but a new release was never tagged.
I think that we should also try to use the normal tracer now instead of the local one.

**Comment by tmigot** [comment]
Yes, we could make a new release here.
What do you mean by "normal tracer"?

**Comment by amontoison** [comment]
https://github.com/JuliaSmoothOptimizers/QuadraticModels.jl/pull/128

**Comment by tmigot** [comment]
Okay, I see. Let me try then.

**Comment by amontoison** [comment]
I opened a PR #132 to quickly test it and another issue now related to the specialized `mul!` for the wrapper `Symmetric`. We need to keep to local tracer.
