### ISSUE TITLE
Adding slack variables to a QuadraticModel

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/QuadraticModels.jl#2]
`SlackModel(qp)` where `qp` is a `QuadraticModel` should return another `QuadraticModel`.

**Comment by abelsiqueira** [comment]
Do we still want this? I forgot the reason.
Returning a QM means creating the specific `Arows`, `Acols` and `Avals` vectors during the constructor (and copies of `Hrows`, etc.), and the current way creates them when `jac_structure` and `jac_coord` are called. If the inplace versions are called, no additional memory is created.

**Comment by dpo** [comment]
Done in #30
