### ISSUE TITLE
Tests with QPS data

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/QuadraticModels.jl#24]
It would be great to add the test problems in QPS format and run the consistency checks.

@geoffroyleconte

**Comment by geoffroyleconte** [comment]
@dpo  
Should I add a starting point argument x0 to QuadraticModel(qp::QPSData)? Because the test problems do have a starting point.

**Comment by dpo** [comment]
Yes, please. That would be great!

**Comment by dpo** [comment]
Done in #22
